#!/usr/bin/env python3
"""Generate six isolated q040 knowledge-only/control Skill Arena comparisons."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import secrets
import sys
from pathlib import Path
from typing import Any, Mapping, Sequence

import yaml


SCRIPT = Path(__file__).resolve()
EVALUATION = SCRIPT.parents[1]
REPO = SCRIPT.parents[3]
OUTPUT = EVALUATION / "skill-arena"
SCHEMA = "semantic-okf-astro-skill-arena-config-manifest/1.0"
FAMILIES = ("legacy", "embeddings", "classical", "adaptive", "entity-graph", "ensemble")
SKILLS = {
    "legacy": "consult-semantic-okf",
    "embeddings": "consult-semantic-okf-embeddings",
    "classical": "consult-semantic-okf-classical",
    "adaptive": "consult-semantic-okf-adaptive",
    "entity-graph": "consult-semantic-okf-entity-graph",
    "ensemble": "consult-semantic-okf-ensemble",
}


class Dumper(yaml.SafeDumper):
    """Indent sequence items so Skill Arena's design validator can parse prompts."""

    def increase_indent(self, flow: bool = False, indentless: bool = False) -> Any:
        return super().increase_indent(flow, False)


class ConfigError(RuntimeError):
    """Describe an invalid accepted build or config-generation input."""


def canonical_json(value: Any) -> str:
    """Serialize JSON deterministically."""

    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False)


def sha256_bytes(value: bytes) -> str:
    """Hash bytes."""

    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    """Hash one file."""

    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_json(path: Path) -> dict[str, Any]:
    """Load one JSON object."""

    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ConfigError(f"cannot load JSON object {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ConfigError(f"expected JSON object: {path}")
    return value


def load_q040(path: Path) -> dict[str, Any]:
    """Load only q040 without exposing evaluator truth."""

    try:
        rows = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ConfigError(f"cannot load hard questions: {exc}") from exc
    row = next((item for item in rows if isinstance(item, dict) and item.get("id") == "q040"), None)
    if not isinstance(row, dict) or set(row) != {"id", "question", "question_type", "qrels"}:
        raise ConfigError("q040 is missing or malformed")
    return {"id": row["id"], "question": row["question"], "question_type": row["question_type"]}


def tree_sha256(root: Path) -> str:
    """Bind one skill package without generated bytecode."""

    rows = [
        {"path": path.relative_to(root).as_posix(), "sha256": sha256_file(path)}
        for path in sorted(item for item in root.rglob("*") if item.is_file() and "__pycache__" not in item.parts)
    ]
    return sha256_bytes(canonical_json(rows).encode("utf-8"))


def response_contract_assertion() -> str:
    """Return the common abstention-safe JSON response contract."""

    return """try {
  const value = JSON.parse(output.trim());
  if (JSON.stringify(Object.keys(value)) !== JSON.stringify(['question_id','answer','evidence'])) return false;
  if (value.question_id !== 'q040' || !Array.isArray(value.evidence)) return false;
  if (value.answer === null) return value.evidence.length === 0;
  if (JSON.stringify(Object.keys(value.answer)) !== JSON.stringify(['summary','claims'])) return false;
  if (typeof value.answer.summary !== 'string' || !value.answer.summary.trim() || !Array.isArray(value.answer.claims)) return false;
  if (!value.answer.claims.every((row) => JSON.stringify(Object.keys(row)) === JSON.stringify(['statement','evidence_indices']) && typeof row.statement === 'string' && row.statement.trim() && Array.isArray(row.evidence_indices) && row.evidence_indices.every(Number.isInteger))) return false;
  return value.evidence.every((row) => JSON.stringify(Object.keys(row)) === JSON.stringify(['source_id','record_id','concept_path','source_path','record_sha256','locator','text_sha256']) && typeof row.source_id === 'string' && typeof row.record_id === 'string' && typeof row.concept_path === 'string' && typeof row.source_path === 'string' && /^[0-9a-f]{64}$/.test(row.record_sha256) && row.locator && typeof row.locator === 'object' && /^[0-9a-f]{64}$/.test(row.text_sha256));
} catch { return false; }"""


def grounded_assertion() -> str:
    """Require a nonempty grounded answer as a separate metric."""

    return """try {
  const value = JSON.parse(output.trim());
  if (value.answer === null || !Array.isArray(value.evidence) || value.evidence.length === 0) return false;
  if (!Array.isArray(value.answer.claims) || value.answer.claims.length === 0) return false;
  return value.answer.claims.every((claim) => claim.evidence_indices.length > 0 && claim.evidence_indices.every((index) => index >= 0 && index < value.evidence.length));
} catch { return false; }"""


def prompt(question: str) -> str:
    """Render one non-leaking, identical prompt for every control/treatment cell."""

    return f"""Answer the Astro technical question below using only the published Semantic OKF snapshot at `knowledge/`. Do not use the web, model memory, or guesses. The snapshot is immutable; do not write into it. Use the available consultation skill if one is installed. If the snapshot cannot support an answer, return `answer: null` and an empty `evidence` array.

Question: {question}

Return JSON only with top-level keys `question_id`, `answer`, and `evidence`, in that order. Set `question_id` to `q040`. A non-null `answer` must contain `summary` and `claims`, in that order. Give a precise 160-320 word synthesis that covers output mode, adapter, route prerendering, endpoint behavior, request-time cookies, and the inverse server-default design. Each claim must contain exactly `statement` and `evidence_indices`; indices are zero-based references into `evidence`. Every evidence row must contain exactly `source_id`, `record_id`, `concept_path`, `source_path`, `record_sha256`, `locator`, and `text_sha256`, copied from an exact validated consultation hit. Keep evidence in first-use order. Do not include benchmark-only relevance labels or unsupported facts."""


def prompt_coverage() -> dict[str, Any]:
    """Declare the intentionally narrow scope of the q040 paired diagnostic."""

    return {
        "schemaVersion": 1,
        "policy": {
            "minimumPrompts": 1,
            "minimumTaskFamilies": 1,
            "minimumNaturalisticCases": 0,
            "requiredCaseKinds": ["boundary-recovery"],
            "maximumPromptWords": 320,
            "maximumPairwiseJaccard": 1.0,
            "maximumSingleFamilyShare": 1.0,
        },
        "cases": [
            {
                "promptId": "q040",
                "caseKind": "boundary-recovery",
                "taskFamily": "conditional-routing-synthesis",
            }
        ],
    }


def config(family: str, run_dir: str, question: Mapping[str, Any]) -> dict[str, Any]:
    """Build one isolated two-arm compare manifest."""

    skill_id = SKILLS[family]
    return {
        "schemaVersion": 1,
        "benchmark": {
            "id": f"semantic-okf-astro-q040-{family}-paired",
            "description": f"A one-question isolated knowledge-only versus {family} consultation diagnostic on frozen Astro q040.",
            "tags": ["compare", "semantic-okf", "astro", "q040", "paired", "isolated", "cli", "no-mcp"],
        },
        "task": {
            "prompts": [
                {
                    "id": "q040",
                    "description": "hard conditional synthesis over three Astro documentation pages",
                    "prompt": prompt(str(question["question"])),
                    "evaluation": {
                        "assertions": [
                            {"type": "javascript", "metric": "response-contract", "value": response_contract_assertion()},
                            {"type": "javascript", "metric": "grounded-answer", "value": grounded_assertion()},
                        ]
                    },
                }
            ]
        },
        "workspace": {
            "sources": [
                {
                    "id": f"{family}-bundle",
                    "type": "local-path",
                    "path": f"{run_dir}/bundles/{family}-a",
                    "target": "/knowledge",
                },
                {
                    "id": "pi-luna-runner",
                    "type": "local-path",
                    "path": "evaluations/semantic-okf-builder/fixtures/workspaces/base/bin",
                    "target": "/bin",
                },
            ],
            "setup": {
                "initializeGit": True,
                "env": {
                    "HF_HUB_OFFLINE": "1",
                    "PYTHONDONTWRITEBYTECODE": "1",
                    "SEMANTIC_OKF_BUNDLE": "$WORKSPACE/knowledge",
                    "TRANSFORMERS_OFFLINE": "1",
                },
            },
        },
        "evaluation": {
            "assertions": [{"type": "is-json", "metric": "response-format"}],
            "requests": 1,
            "timeoutMs": 600000,
            "tracing": False,
            "maxConcurrency": 1,
            "noCache": True,
        },
        "comparison": {
            "profiles": [
                {
                    "id": "knowledge-only-control",
                    "description": "Same immutable bundle with no declared consultation skill.",
                    "isolation": {"inheritSystem": False},
                    "capabilities": {},
                    "output": {
                        "tags": ["control", "knowledge-only"],
                        "labels": {"capability": "none", "causal_role": "passive-control"},
                    },
                },
                {
                    "id": f"{family}-consult-treatment",
                    "description": f"Same immutable bundle with only {skill_id} installed.",
                    "isolation": {"inheritSystem": False},
                    "capabilities": {
                        "skills": [
                            {
                                "source": {
                                    "type": "local-path",
                                    "path": f"skills/{skill_id}",
                                    "skillId": skill_id,
                                },
                                "install": {"strategy": "workspace-overlay"},
                            }
                        ]
                    },
                    "output": {
                        "tags": ["treatment", family, "cli", "no-mcp"],
                        "labels": {"capability": skill_id, "causal_role": "treatment"},
                    },
                },
            ],
            "variants": [
                {
                    "id": "pi-luna-only",
                    "description": "The same PI GPT-5.6 Luna route for both isolated cells.",
                    "agent": {
                        "adapter": "pi",
                        "model": "openai-codex/gpt-5.6-luna",
                        "executionMethod": "command",
                        "commandPath": "bin/pi-luna.ps1",
                        "sandboxMode": "read-only",
                        "approvalPolicy": "never",
                        "webSearchEnabled": False,
                        "networkAccessEnabled": True,
                        "reasoningEffort": "medium",
                        "additionalDirectories": [],
                        "cliEnv": {"PI_MODEL_TIMEOUT_SECONDS": "600"},
                        "envPassthrough": ["SEMANTIC_OKF_PYTHON", "SEMANTIC_OKF_HF_HUB_CACHE"],
                        "config": {},
                    },
                    "output": {
                        "tags": ["pi", "gpt-5.6-luna", "isolated", "cli", "no-mcp"],
                        "labels": {"variantDisplayName": "PI GPT-5.6 Luna"},
                    },
                }
            ],
        },
    }


def atomic_write(path: Path, content: str) -> None:
    """Publish one generated config or manifest atomically."""

    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{secrets.token_hex(5)}.tmp")
    try:
        temporary.write_text(content, encoding="utf-8", newline="\n")
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def generate(args: argparse.Namespace) -> dict[str, Any]:
    """Generate and bind every paired config."""

    build = load_json(args.build_report)
    if build.get("status") != "pass" or build.get("authoritative_core_parity") is not True:
        raise ConfigError("build report is not an accepted all-family parity run")
    run_dir = build.get("run_dir")
    if not isinstance(run_dir, str) or not (REPO / run_dir).is_dir():
        raise ConfigError("build report run_dir is unavailable")
    question = load_q040(args.questions)
    coverage = prompt_coverage()
    coverage_path = args.output / "prompt-coverage.json"
    atomic_write(
        coverage_path,
        json.dumps(coverage, ensure_ascii=False, sort_keys=True, indent=2) + "\n",
    )
    outputs = []
    for family in FAMILIES:
        payload = yaml.dump(
            config(family, run_dir, question),
            Dumper=Dumper,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
            width=1000,
        )
        path = args.output / f"q040-{family}-paired.yaml"
        atomic_write(path, payload)
        skill = REPO / "skills" / SKILLS[family]
        outputs.append(
            {
                "family": family,
                "config": path.relative_to(REPO).as_posix(),
                "config_sha256": sha256_file(path),
                "skill_id": SKILLS[family],
                "skill_tree_sha256": tree_sha256(skill),
                "bundle": f"{run_dir}/bundles/{family}-a",
            }
        )
    manifest = {
        "schema_version": SCHEMA,
        "status": "pass",
        "interpretation": "Each file is an isolated same-bundle knowledge-only control versus one-skill treatment. The six files are separate paired diagnostics, never an all-skills causal portfolio.",
        "question": question,
        "question_source": {
            "path": args.questions.relative_to(REPO).as_posix(),
            "sha256": sha256_file(args.questions),
        },
        "prompt_coverage": {
            "path": coverage_path.relative_to(REPO).as_posix(),
            "sha256": sha256_file(coverage_path),
            "scope": "one-question boundary diagnostic, not an aggregate capability estimate",
        },
        "build_report": {
            "path": args.build_report.relative_to(REPO).as_posix(),
            "sha256": sha256_file(args.build_report),
            "run_dir": run_dir,
        },
        "model": "openai-codex/gpt-5.6-luna",
        "requests_per_cell": 1,
        "comparisons": outputs,
    }
    atomic_write(args.output / "q040-config-manifest.json", json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=2) + "\n")
    return manifest


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse generator arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build-report", type=Path, default=EVALUATION / "reports/build-comparison.json")
    parser.add_argument("--questions", type=Path, default=EVALUATION / "benchmark/hard-questions.jsonl")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args(argv)
    for name in ("build_report", "questions", "output"):
        setattr(args, name, getattr(args, name).resolve())
    return args


def main(argv: Sequence[str] | None = None) -> int:
    """Generate the accepted configs and manifest."""

    args = parse_args(argv)
    try:
        report = generate(args)
    except (ConfigError, OSError, UnicodeError, ValueError, TypeError, KeyError) as exc:
        print(json.dumps({"status": "error", "error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 1
    print(json.dumps({"status": "pass", "configs": len(report["comparisons"]), "output": str(args.output)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
