from __future__ import annotations

import json
import shlex
from pathlib import Path

from .base import SourceAdapter


class TelevisionSource(SourceAdapter):
    """Adapter that generates Television channel definitions for ``tv``."""

    def sync(self) -> dict[str, object]:
        self.clear_source_dir()

        channel_name = self.config.get("channel") or self.source["title"]
        channel_slug = self.source["id"].removeprefix("television-")
        channel_path = self.raw_dir / f"{channel_slug}.toml"
        manifest_path = self.raw_dir / "commands.json"
        readme_path = self.raw_dir / "README.md"

        self.write_text(channel_path, self._build_channel_toml(channel_name))
        manifest = self._build_command_manifest(channel_name, channel_path)
        self.write_json(manifest_path, manifest)
        self.write_text(
            readme_path,
            self._build_readme(channel_name, channel_path.name, manifest),
        )

        return self.finalize_sync(
            {
                "channel": channel_name,
                "files": 3,
                "channel_file": str(channel_path),
                "command_manifest": str(manifest_path),
                "readme": str(readme_path),
            }
        )

    def _build_channel_toml(self, channel_name: str) -> str:
        lines = [
            "[metadata]",
            f'name = "{_escape_toml(channel_name)}"',
            f'description = "{_escape_toml(self.config.get("description") or "")}"',
            "",
            "[source]",
            f'command = "{_escape_toml(self.config["source_command"])}"',
        ]
        source_display = self.config.get("source_display")
        if source_display:
            lines.append(f'display = "{_escape_toml(source_display)}"')
        preview_command = self.config.get("preview_command")
        if preview_command:
            lines.extend(
                [
                    "",
                    "[preview]",
                    f'command = "{_escape_toml(preview_command)}"',
                ]
            )
        action_command = self.config.get("action_command")
        if action_command:
            lines.extend(
                [
                    "",
                    "[keybindings]",
                    'ctrl-o = "actions:open"',
                    "",
                    "[actions.open]",
                    f'command = "{_escape_toml(action_command)}"',
                    'mode = "execute"',
                ]
            )
        return "\n".join(lines) + "\n"

    def _build_command_manifest(self, channel_name: str, channel_path: Path) -> dict[str, str]:
        quoted_channel_path = _shell_quote(str(channel_path))
        install_macos = (
            'config_dir="${TELEVISION_CONFIG:-${XDG_CONFIG_HOME:-$HOME/.config}/television}"; '
            'mkdir -p "$config_dir/cable" && '
            f'cp {quoted_channel_path} "$config_dir/cable/{channel_path.name}"'
        )
        install_windows = (
            "$configDir = if ($env:TELEVISION_CONFIG) { $env:TELEVISION_CONFIG } "
            "elseif ($env:XDG_CONFIG_HOME) { Join-Path $env:XDG_CONFIG_HOME 'television' } "
            "else { Join-Path $env:LOCALAPPDATA 'television\\config' }; "
            "$cableDir = Join-Path $configDir 'cable'; "
            "New-Item -ItemType Directory -Force -Path $cableDir | Out-Null; "
            f'Copy-Item -Force "{channel_path}" (Join-Path $cableDir "{channel_path.name}")'
        )
        manifest = {
            "sync": self.source["update_command"],
            "install_macos": install_macos,
            "install_windows": install_windows,
            # Preserve the original manifest keys for existing consumers.
            "install_unix": install_macos,
            "install_powershell": install_windows,
            "run_after_install": f"tv {channel_name}",
            "run_inline": self._build_inline_run_command(),
        }
        return manifest

    def _build_readme(
        self,
        channel_name: str,
        channel_filename: str,
        manifest: dict[str, str],
    ) -> str:
        """Render standalone install and verification instructions for a channel."""

        return (
            f"# {channel_name} Television channel\n\n"
            "This bundle was generated by `know sync television`. The TOML cable and "
            "commands in `commands.json` are the reproducible source of truth.\n\n"
            f"- Cable: `{channel_filename}`\n"
            "- Command manifest: `commands.json`\n\n"
            "## Install on macOS\n\n"
            "```sh\n"
            f"{manifest['install_macos']}\n"
            "```\n\n"
            "## Install on Windows PowerShell\n\n"
            "```powershell\n"
            f"{manifest['install_windows']}\n"
            "```\n\n"
            "## Verify\n\n"
            "```text\n"
            "tv --version\n"
            "tv list-channels\n"
            f"{manifest['run_after_install']}\n"
            "```\n"
        )

    def _build_inline_run_command(self) -> str:
        parts = ["tv", f"--source-command={_shell_quote(self.config['source_command'])}"]
        source_display = self.config.get("source_display")
        if source_display:
            parts.append(f"--source-display={_shell_quote(source_display)}")
        preview_command = self.config.get("preview_command")
        if preview_command:
            parts.append(f"--preview-command={_shell_quote(preview_command)}")
        return " ".join(parts)


def _escape_toml(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _shell_quote(value: str) -> str:
    return shlex.quote(value)
